### ISSUE TITLE
Review geoId 2018

### ISSUE THREAD

**Issue by olafveerman** [developmentseed/af-elections-data#4]
Review the provinces and districts of 2018, and ensure that they use the `419 AGCHO` standard.

See: https://github.com/developmentseed/af-elections/issues/97#issuecomment-479578737

**Comment by Rub21** [comment]
@olafveerman  We have reviewed  the file : https://github.com/developmentseed/af-elections-data/blob/master/2018-wolesi-jirga/districts.csv

There were many different districts `geoId` but the Id  in `districts.csv` is the same as the `geoId` in `419 AGCHO `  👇 
![Screen Shot 2019-04-04 at 4 57 30 PM](https://user-images.githubusercontent.com/1152236/55591689-cf86aa80-56fb-11e9-86b2-ef783528f1e0.png)

These are the districts which We could not find the geoId

304 | SAYID KHAIL | 3
-- | -- | --
623 | SPIN GHAR | 6
1314 | GARDA SIRAY | 13
1315 | ROHANI BABA | 13
2403 | GIZAB | 24
3406 | DULARAM | 34
10101 | Nahia 01 | 1
10102 | Nahia 02 | 1
10103 | Nahia 03 | 1
10104 | Nahia 04 | 1
10105 | Nahia 05 | 1
10106 | Nahia 06 | 1
10107 | Nahia 07 | 1
10108 | Nahia 08 | 1
10109 | Nahia 09 | 1
10110 | Nahia 10 | 1
10111 | Nahia 11 | 1
10112 | Nahia 12 | 1
10113 | Nahia 13 | 1
10114 | Nahia 14 | 1
10115 | Nahia 15 | 1
10116 | Nahia 16 | 1
10117 | Nahia 17 | 1
10118 | Nahia 18 | 1
10119 | Nahia 19 | 1
10121 | Nahia 21 | 1
10122 | Nahia 22 | 1
35999 | Kuchi | 35
36999 | Sikh | 36

but i could assume the geoId for that districts are the colum `id`., what do you think?  Also We addedd the names for each district acoording to `419 AGCHO`   it is in the colum [`419Name`](https://github.com/developmentseed/af-elections-data/blob/922cd37187fa0bb093d8ee9212ce91e4e04fb351/2018-wolesi-jirga/districts.csv) if you area agree we could update the name too. 
PR: https://github.com/developmentseed/af-elections-data/pull/10

cc. @vgeorge

**Comment by vgeorge** [comment]
@Rub21, I found more info about these districts:

- SAYID KHAIL: Located in Sayed Karam, 1306 (district look up sheet);
- SPIN GHAR: Jaji Maydan, 1413 (Zazi district, [found on osm](https://www.openstreetmap.org/search?query=spin%20ghar#map=19/34.00613/69.71304))
- GARDA SIRAY: Zadran, 1305 (district look up sheet);
- ROHANI BABA: Zurmat, 1303 (district look up sheet);
- GIZAB: Gezab, 2506 (district look up sheet);
- DULARAM: Dilaram, 3406  (district look up sheet);
- Nahia 01, 02, etc: These are areas inside Jalalabad, 0601 ([ref](http://jalalabad-m.gov.af/en/page/5825))
- Kuchi and Sikh: are "fake" districts used to represent Kuchi and Sikn ethnic groups.

**Comment by Rub21** [comment]
Thank you for the help @vgeorge !!

> SAYID KHAIL: Located in Sayed Karam, 1306 (district look up sheet); 

☝️  it is in the Province of Paktia but actually, it should be in Parwan province


> SPIN GHAR: Jaji Maydan, 1413 (Zazi district, found on osm)
I think it would be `0623`
![Screen Shot 2019-04-05 at 9 28 19 AM](https://user-images.githubusercontent.com/1152236/55635027-5af84e00-5785-11e9-87fc-1df8254d1fdd.png)

> GARDA SIRAY: Zadran, 1305 (district look up sheet);

I think it should be `13141`  because `1305` is for `Zadran` 
Zadran
![image](https://user-images.githubusercontent.com/1152236/55635759-1b326600-5787-11e9-9851-267373d0351e.png)


> ROHANI BABA: Zurmat, 1303 (district look up sheet);
`1303` belongs to `Zurmat`
![image](https://user-images.githubusercontent.com/1152236/55636185-f094dd00-5787-11e9-9fa3-bebcde2224f9.png)
 
> GIZAB: Gezab, 2506 (district look up sheet);

This Gizab is in `Urozgan` province , the gizab which is missing is in `Daykundi` province. 

> DULARAM: Dilaram, 3406 (district look up sheet);
👍 


> Nahia 01, 02, etc: These are areas inside Jalalabad, 0601 (ref)

not sure, We have added  Nahia 01 and others with `0101` : https://github.com/developmentseed/af-elections-data/pull/10#pullrequestreview-223061965

**Comment by Rub21** [comment]
@olafveerman @vgeorge  These are the final changes: Take a look and merge it:
https://github.com/developmentseed/af-elections-data/pull/10/files

**Comment by olafveerman** [comment]
Closing this issue. We can test in the browser and revisit if necessary.
